# Generated by Django 4.2.2 on 2023-06-25 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_elecciones_feuc_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consejo_FEUC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Votaciones_FEUC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votacion', models.CharField(max_length=1000)),
                ('votos', models.JSONField()),
                ('consejo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.consejo_feuc')),
            ],
        ),
    ]
