# Generated by Django 4.2.2 on 2023-06-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elecciones_FEUC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('vuelta', models.IntegerField()),
                ('quorum', models.FloatField()),
                ('numero_votantes', models.IntegerField()),
                ('porcentaje_mg', models.FloatField()),
                ('votos_mg', models.IntegerField()),
                ('porcentaje_sdd', models.FloatField()),
                ('votos_sdd', models.IntegerField()),
                ('porcentaje_avnzr', models.FloatField()),
                ('votos_avnzr', models.IntegerField()),
                ('porcentaje_nau', models.FloatField()),
                ('votos_nau', models.IntegerField()),
                ('porcentaje_surgencia', models.FloatField()),
                ('votos_surgencia', models.IntegerField()),
                ('porcentaje_nulo', models.FloatField()),
                ('votos_nulo', models.IntegerField()),
                ('porcentaje_blanco', models.FloatField()),
                ('votos_blanco', models.IntegerField()),
            ],
        ),
    ]
